
spring:
  application:
    name: pet
  jackson:
    default-property-inclusion: non_null
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 970105
    url: jdbc:mysql://127.0.0.1:3306/pet?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8


  redis:
    host: 127.0.0.1
    port: 6379
  pool:
    max-active: 8
    min-idle: 0
    max-idle: 8
    max-wait: -1

server:
  port: 9009

qiniu:
  accesskey: 7jezCDrKwFvOCMHZD7UwaQ1WwhaCBcaO5AL3Q1BK
  secretkey: 0YWqk9XIoiNAbibwwEViVgzoYjw0Uo2WyBDJaPcw
  bucket: pet
  domain: http://prue4i2lu.bkt.clouddn.com/